#!/bin/bash

logfile=$1
if [ -z "$logfile" ]; then
	echo "Specify a filename"
	exit 1
fi

sed -i -r '/(error|ignoring|, ignored|checkpvs|Invalid|Some entity is stuck|deprecated|packetlog overflow|already defined|unknown surfaceparm|failed to load|no tooltip set|autogenerated mapinfo|Failed to load font-file|Added packfile|GLSL shader|nasty filename rejected|\^7plane|walk to any goal, going to a near waypoint)/ d' "$logfile"
